name: 'Generate Coverage Summary Markdown'
description: 'Generate a Markdown summary from a coverage JSON file'
inputs:
  json-file:
    description: 'The path to the coverage JSON file'
    required: true
  coverage-threshold:
    description: 'The coverage threshold for emoji inclusion'
    required: true
  issue-number:
    description: 'The issue number to comment on'
    required: true
  token:
    description: 'GITHUB_TOKEN or a repo scoped PAT.'
    default: ${{ github.token }}
  repository:
    description: 'The full name of the repository in which to create or update a comment.'
    default: ${{ github.repository }}

runs:
  using: 'node20'
  main: 'dist/index.js'
